### PR TITLE
Fix Proxy creation panicing on target not callable

### LINKED ISSUE #306: Proxy creation panics on target not callable
The following tc39 [test panics](https://github.com/tc39/test262/blob/f37edcb486db80d7aaf50147df14268a910556a9/test/built-ins/Proxy/create-target-is-not-callable.js) which unfortunately is from after the current commit used in goja :(

### PR DESCRIPTION
**Pull request by MStoykov**
fixes #306

### CODE REVIEW

File: proxy.go [hunk 1]
```diff
@@ -848,7 +848,7 @@ func (p *proxyObject) assertConstructor() func(args []Value, newTarget *Object)
 
 func (p *proxyObject) apply(call FunctionCall) Value {
 	if p.call == nil {
-		p.val.runtime.NewTypeError("proxy target is not a function")
+		panic(p.val.runtime.NewTypeError("proxy target is not a function"))
```
Comment (MStoykov) [inline proxy.go:851]: I didn't find another occurrence of this in the code
